import { Link } from 'react-router-dom';
import { panelStyle } from '../utils/ui.jsx';

export default function TermsOfServicePage() {
  return (
    <div className="fade-in" style={{ maxWidth: '960px', margin: '0 auto', padding: 'var(--s8) var(--s6)', display: 'flex', flexDirection: 'column', gap: 'var(--s6)' }}>
      {/* Breadcrumb & Header */}
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, color: 'var(--text-muted)', marginBottom: 12 }}>
          <Link to="/" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>Terminal</Link>
          <span>/</span>
          <span style={{ color: 'var(--text)' }}>Terms of Service</span>
        </div>
        <h1 className="gradient-text" style={{ fontSize: 'var(--fs-h1)', fontWeight: 800, margin: '0 0 8px' }}>
          Terms of Service &amp; Market Disclaimers
        </h1>
        <p style={{ fontSize: 'var(--fs-body)', color: 'var(--text-muted)', margin: 0 }}>
          Effective: September 2026 · Engineered by Sahil
        </p>
      </div>

      <div style={{ ...panelStyle, padding: 'var(--s8)', display: 'flex', flexDirection: 'column', gap: 'var(--s6)', lineHeight: 1.7 }}>
        <section>
          <h2 style={{ fontSize: 'var(--fs-h2)', fontWeight: 700, color: 'var(--text)', marginBottom: 8 }}>
            1. Informational &amp; Research Purposes Only
          </h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            The Indian Stock &amp; Intraday Intelligence Terminal, engineered by <strong>Sahil</strong>, is a research, technical analysis, and telemetry observation tool. The signals generated by the scanner (e.g., ORB, VWAP pullbacks, RVOL spikes, and ENTER triggers) are rules-based mathematical computations, <strong>not financial recommendations, buy/sell orders, or portfolio advisory services</strong>.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: 'var(--fs-h2)', fontWeight: 700, color: 'var(--text)', marginBottom: 8 }}>
            2. Statutory Regulatory Disclaimers (SEBI Compliance)
          </h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            Neither Sahil nor StockAnalyzer is registered with the Securities and Exchange Board of India (SEBI) as a Research Analyst or Investment Adviser under SEBI (Investment Advisers) Regulations, 2013. Users are strictly advised to consult certified, SEBI-registered financial advisers before allocating real capital or executing derivative/equity trades.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: 'var(--fs-h2)', fontWeight: 700, color: 'var(--text)', marginBottom: 8 }}>
            3. Market Risk &amp; High-Frequency Volatility
          </h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            Securities trading in Indian stock exchanges (NSE and BSE), particularly Intraday, Futures, and Options trading, carries substantial capital risk. Market participants may lose partial or total invested capital due to execution slippage, volatility expansions, gap openings, or liquidity dry-ups. Past statistical performance or historical backtests do not guarantee future market behavior.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: 'var(--fs-h2)', fontWeight: 700, color: 'var(--text)', marginBottom: 8 }}>
            4. Data Latency &amp; Third-Party Providers
          </h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            Exchange data, order-book depths, and company statements are retrieved through multi-tier public feeds and caching layers. Feeds may be delayed by 1 to 15 minutes depending on upstream provider status. Sahil disclaims all liability for losses incurred due to transmission delays, internet failures, or upstream feed outages.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: 'var(--fs-h2)', fontWeight: 700, color: 'var(--text)', marginBottom: 8 }}>
            5. Intellectual Property &amp; Handcrafted Code
          </h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            The UI architecture, scanner algorithms, visual charts, and telemetry designs are handcrafted and copyrighted by <strong>Sahil</strong>. For source code license details or academic research usage, refer to <a href="/humans.txt" style={{ color: 'var(--accent-strong)', textDecoration: 'none' }}>humans.txt</a> and project licenses.
          </p>
        </section>
      </div>
    </div>
  );
}
